// src/views/admin/Alerts.svelte
<script>
  import { toast } from '../../stores/Toast';
  import { onMount } from 'svelte';
  import OFetch from '../../helpers/fetch';
  import config from '../../helpers/config';
  import { formatTimestamp } from '../../helpers/formatTimestamp.js';
  import get_publish_date from '../../helpers/publishedDate';

  let alerts = [];
  let newAlert = '';
  let editItem = undefined;
  let get_char_left = 500;
  let updatingBillboard = false;

  onMount(async () => {
    fetchAllAlerts();
  });

  const fetchAllAlerts = async () => {
    try {
      alerts = await OFetch(`${config.BASE_URL}/admin/alert/`, 'GET');
      console.log(alerts);
    } catch (error) {
      console.warn(error);
      toast.setToast('En feil har oppstått', 'error');
    }
  };
  const toggleIsLive = async (alert) => {
    alert.is_live = !alert.is_live;
    try {
      const result = await OFetch(
        `${config.BASE_URL}/admin/alert/${alert.id}`,
        'PATCH',
        alert
      );
      //await fetchAllAlerts();
      toast.setToast('Ny endring lagret', 'success');
    } catch (error) {
      console.warn(error);
      toast.setToast('En feil har oppstått', 'error');
    }
  };
  const createAlert = async () => {
    if (newAlert === '') {
      toast.setToast('Meldingen kan ikke være tom', 'error');
      return;
    }
    try {
      const result = await OFetch(
        `${config.BASE_URL}/admin/alert`,
        'POST',
        {
          message: newAlert
        }
      );
      toast.setToast('Ny melding lagret', 'success');
      await fetchAllAlerts();
      newAlert = '';
    } catch (error) {
      console.warn(error);
      toast.setToast('En feil har oppstått', 'error');
    }
  };

  const updateBillboard = async () => {
    updatingBillboard = true;
    const activeAlerts = alerts.filter((alert) => alert.is_live);
    const message = activeAlerts.map((alert) => alert.message).join(' ');
    const now = new Date();
    const hours = now.getHours();
    const minutes = now.getMinutes();
    const seconds = now.getSeconds();
    const time = `${hours}:${minutes < 10 ? `0${minutes}` : minutes}:${seconds}`;
    const body = {
      message: message,
      time,
    };
    try {
      const result = await OFetch(
        `${config.BASE_URL}/admin/panoramasign/message`,
        'PATCH',
        body
      );
      console.log(result);
      toast.setToast('Ny melding lagret', 'success');
    } catch (error) {
      console.warn(error);
      toast.setToast('En feil har oppstått', 'error');
    }
    updatingBillboard = false;
  };

  const deleteAlert = async (alert) => {
    try {
      const result = await OFetch(
        `${config.BASE_URL}/admin/alert/${alert.id}`,
        'DELETE'
      );
      toast.setToast('Slettet melding', 'success');
      await fetchAllAlerts();
    } catch (error) {
      console.warn(error);
      toast.setToast('En feil har oppstått', 'error');
    }
  };
  const editAlert = async () => {
    try {
      const result = await OFetch(
        `${config.BASE_URL}/admin/alert/${editItem.id}`,
        'PATCH',
        editItem
      );
      toast.setToast('Endring lagret', 'success');
      await fetchAllAlerts();
    } catch (error) {
      console.warn(error);
      toast.setToast('En feil har oppstått', 'error');
    }

    editItem = undefined;
  };
  const deleteNonActiveAlerts = async () => {
    for (let i = 0; i < alerts.length; i++) {
      if (!alerts[i].is_live) await deleteAlert(alerts[i]);
    }
  };
</script>

<div class="admin-alerts">
  <div class="admin-add">
    <h2>Oppdater meldinger</h2>
    <p>
      Meldingene publiseres på <a href="https://tavle.oppdalskisenter.no"
        >oppdalskisenter.no/loypestatus</a
      >
    </p>
    <textarea
      class="oppdal-input"
      type="text"
      name="message"
      placeholder="Skriv en oppdatering her (max 150 tegn)"
      maxlength="150"
      bind:value={newAlert}
    />
    <div class="flex row justify-between">
      <div class="button-wrapper">
        <button class="admin-button" on:click={createAlert}>Publiser</button>
      </div>
      <div class="button-wrapper">
        <button class={`admin-button`} style={updatingBillboard ? "background-color: gray;" : ""} disabled={updatingBillboard} on:click={updateBillboard}
          >Oppdater tavle</button
        >
      </div>
    </div>
  </div>

  <div class="history">
    <h3>Historikk</h3>
    <table class="admin-table">
      <tbody>
        {#each alerts as alert}
          <tr class="admin-table-row">
            <th
              ><p class="table-timestamp">
                {get_publish_date(alert.timestamp)}
              </p></th
            >
            <th><p>{alert.message}</p></th>
            <th class="toggle-col">
              <div
                class="toggle-text"
                style={alert.is_live ? 'color: #22A830' : 'color: #BABABA'}
              >
                <p>{alert.is_live ? 'Aktiv' : 'Ikke aktiv'}</p>
              </div>
              <div>
                <label class="toggle-switch"
                  ><input
                    type="checkbox"
                    on:change={() => toggleIsLive(alert)}
                    bind:checked={alert.is_live}
                  /><span class="slider" /></label
                >
              </div>
            </th>
            <th on:click={() => (editItem = alert)}
              ><i class="fas fa-edit" /></th
            >
            <th on:click={() => deleteAlert(alert)}
              ><i class="fas fa-trash-alt" /></th
            >
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
  <!--<button class="admin-text-button" on:click="{deleteNonActiveAlerts}">Slett alle meldinger som ikke er aktiv</button>-->
</div>

{#if editItem}
  <div class="admin-blur" on:click={() => (editItem = undefined)} />
  <div class="admin-edit">
    <h3 class="sub-header">Rediger melding</h3>
    <p class="small-info">max. 500 tegn</p>
    <textarea
      class="oppdal-input"
      type="text"
      name="message"
      bind:value={editItem.message}
    />
    <div>
      <button class="admin-button" on:click={() => (editItem = undefined)}
        >Avbryt</button
      >
      <button class="admin-button" on:click={editAlert}>Lagre endring</button>
    </div>
  </div>
{/if}

<style>
  .history {
    overflow: scroll;
  }
  .admin-alerts {
    margin: 1rem 0 0 0;
  }
  .admin-alerts > * {
    margin: 1rem 0 0 0;
  }
  .toggle-switch {
    position: relative;
    display: inline-block;
    width: 60px;
    height: 30px;
  }

  .toggle-switch input {
    opacity: 0;
    width: 0;
    height: 0;
  }

  .slider {
    position: absolute;
    cursor: pointer;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: #ccc;
    -webkit-transition: 0.4s;
    transition: 0.4s;
    border-radius: 34px;
  }

  .slider:before {
    position: absolute;
    content: '';
    height: 22px;
    width: 22px;
    left: 4px;
    top: 4px;
    background-color: white;
    -webkit-transition: 0.4s;
    transition: 0.4s;
    border-radius: 50%;
  }

  input:checked + .slider {
    background-color: #2fc93e;
  }

  input:checked + .slider:before {
    -webkit-transform: translateX(30px);
    -ms-transform: translateX(30px);
    transform: translateX(30px);
  }
  .toggle-col {
    display: flex;
    flex-direction: row;
    justify-content: flex-end;
    align-items: center;
    padding-right: 4rem;
  }
  .toggle-text {
    padding-right: 1rem;
  }
  @media only screen and (max-width: 1000px) {
    .admin-alerts {
      padding: 1rem;
    }
  }
</style>

// pages/admin/alerts.vue
<template>
  <div>
    <div v-if="isLoading" class="absolute w-full h-full flex justify-center items-center">
      <div class="w-full h-full absolute bg-gray-800 z-10 opacity-70" />
      <loading class="z-20" :active="isLoading" is-full-page />
    </div>
    <div class="dark:bg-gray-800 bg-white dart:text-white">
      <admin-navbar>
        <span>Meldinger</span>
        <template v-slot:actions>
          <button :disabled="isLoading"
            :class="`py-2 px-4 mt-2 rounded-full text-white ${!isLoading ? 'bg-yellow-600 dark:bg-yellow-700' : 'bg-gray-400 dark:bg-gray-300'}`"
            @click="updateBillboard">Send til tavle</button>
        </template>
      </admin-navbar>
    </div>
    <div class="flex flex-col items-center font-sans dark:bg-gray-700 bg-white dark:text-white">
      <max-wrapper>
        <h1 class="text-xl font-bold">Oppdater meldinger</h1>
        <p class="pb-2">meldinger publiseres på <a class="underline"
            href="https://tavle.oppdalskisenter.no">tavle.oppdalskisenter.no</a></p>
        <textarea
          class="flex justify-between align-center px-4 w-full max-w-screen-xl dark:bg-gray-800 rounded-2xl bg-gray-200"
          v-model="input" placeholder="Skriv inn viktig melding for tavle og/eller web (max 150 tegn)" maxlength="150"></textarea>
        <button :disabled="!input"
          :class="`py-2 px-4 mt-2 rounded-full ${!!input ? 'bg-yellow-600 dark:bg-yellow-700' : 'bg-gray-400 dark:bg-gray-300'} text-white`"
          @click="() => addAlert(input)">Lagre</button>
        <p class="py-2">Huk av meldinger som skal være aktive</p>
        <div class="py-4 w-full max-w-screen-xl">
          <h1 class="text-l font-bold">Historikk</h1>
          <div class="w-full max-w-screen-xl text-left">
            <div>
              <div v-for="(item, index) in alerts" :key="item.id"
                :class="`flex w-full justify-between py-3 px-2 rounded-2xl ${index % 2 && 'dark:bg-gray-800 bg-gray-200'}`">
                <span class="w-48" v-if="item.timestamp">{{ item.timestamp && get_publish_date(item.timestamp)
                }}</span>
                <span class="flex-1 justify-start">{{ item.message }}</span>
                <select name="billboard" id="billboard" class="text-gray-800" :value="item.billboard"
                  @change="(e) => limitToBillboard(item, e)">
                  <optgroup>
                    <option :value="null">Alle tavler</option>
                    <option v-for="billboard in billboards" :value="billboard.id">{{ billboard.name }}</option>
                  </optgroup>
                </select>
                <div class="pl-2">
                  <input type="checkbox" :checked="!!item.is_live" @change="() => toggleAlert(item)" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </max-wrapper>
    </div>
  </div>
</template>
<script>
import Loading from 'vue-loading-overlay';
import BASE_URL from '../../helpers/baseurl'
import AuthFetch from '../../helpers/fetch'
import get_publish_date from '../../helpers/publishedDate.js'
export default {
  middleware({ redirect }) {
    if (!window.localStorage.getItem("token")) {
      redirect("/admin/login")
    }
  },
  components: {
    Loading
  },
  data: () => ({
    input: '',
    alerts: [],
    updatingBillboard: false,
    updating: false,
    billboards: []
  }),
  async fetch() {
    await this.fetchBillboards()
    await this.fetchAlerts()
  },
  computed: {
    isLoading() {
      if (this.updating === true) return true
      if (this.updatingBillboard === true) return true
      return false
    }
  },
  methods: {
    async addAlert(input) {
      if (!input) return
      this.updating = true
      await AuthFetch(
        `${BASE_URL}/admin/alert`,
        'POST',
        {
          message: input
        }
      )
      await this.fetchAlerts()
    },
    async fetchBillboards() {
      let res = await AuthFetch(
        BASE_URL + "/billboards",
        'GET'
      )
      this.billboards = res
    },
    async fetchAlerts() {
      let res = await AuthFetch(
        BASE_URL + "/admin/alert",
        'GET'
      )
      this.alerts = res
      this.updating = false
    },
    get_publish_date,
    async toggleAlert(item) {
      this.updating = true
      let newStatus = !!item.is_live
      const newStatusAsNumber = !newStatus ? 1 : 0
      await AuthFetch(
        `${BASE_URL}/admin/alert/${item.id}`,
        'PATCH',
        {
          ...item,
          ...{
            is_live: newStatusAsNumber
          }
        }
      )
      await this.fetchAlerts()
    },
    async limitToBillboard(item, e) {
      this.updating = true
      const billboard = parseInt(e.target.value)
      await AuthFetch(
        `${BASE_URL}/admin/alert/${item.id}`,
        'PATCH',
        {
          ...item,
          ...{
            billboard: billboard
          }
        }
      )
      await this.fetchAlerts()
    },
    async updateBillboard() {
      this.updatingBillboard = true
      const activeAlerts = this.alerts.filter(item => item.is_live)
      const now = new Date()
      const hours = now.getHours()
      const minutes = now.getMinutes()
      const seconds = now.getSeconds()
      const time = `${hours}:${minutes < 10 ? `0${minutes}` : minutes}:${seconds}`
      if (activeAlerts.some(item => item.billboard)) {
        for (var i = 0; i < this.billboards.length; i++) {
          const billboard = this.billboards[i]
          let messages = []
          for (var y = 0; y < activeAlerts.length; y++) {
            let activeAlert = activeAlerts[y]
            if (activeAlert.billboard == billboard.id) {
              messages.push(activeAlert.message)
            }
          }
          const message = messages.join('     ')
          const body = {
            message: message,
            time,
          }
          await AuthFetch(
            `${BASE_URL}/admin/panoramasign/message/${billboard.port}`,
            'PATCH',
            body
          )
        }
      } else {
        let message = activeAlerts.map((alert) => alert.message).join('     ')
        const body = {
          message: message,
          time,
        }
        try {
          await AuthFetch(
            `${BASE_URL}/admin/panoramasign/message`,
            'PATCH',
            body
          )
        } catch (error) {
          console.warn(error)
        }
      }
      this.updatingBillboard = false
    }
  }
}
</script>
