// src/components/Footer.svelte
<footer class="footer">
    <div class="contact-information">
        <h2>Kontakt oss</h2>
        <div>
            <p class="footer-big">Tlf: +47 72 40 44 80</p>
            <p class="footer-small">E-post: post@oppdalskisenter.no</p>
        </div>
        <div>
            <p class="footer-big">Gondolbane, Hovden</p>
            <p class="footer-small">Gamle Kongeveg 53, 7340 Oppdal</p>
        </div>
        <div>
            <p class="footer-big">Servicesenter Vangslia</p>
            <p class="footer-small">Kjerkvegen 112, 7340 Oppdal</p>
        </div>
        <div>
            <a target="_blank" href="https://facebook.com/oppdal/"><i class="fab fa-facebook"></i></a>
            <a target="_blank" href="https://instagram.com/oppdal_skisenter/"><i class="fab fa-instagram"></i></a>
            <p class="footer-small">Oppdal skisenter &copy; 2021</p>
        </div>
    </div>
    <div class="map">
        <div id="map"></div>
    </div>
</footer>


<style>
    .footer {
        margin-top: auto;
        display: flex;
        justify-content: center;
        align-items: center;
        background: #4C546D;
        color: #F4F8FF;
        min-height: 730px;
    }
    .contact-information > h2, div, div > p, div > a{
        color: #F4F8FF;
    }
    .contact-information {
        width: 100%;
        height: 500px;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        text-align: center;
    }

    .footer-big {
        font-family: Work Sans;
        font-style: normal;
        font-weight: 600;
        font-size: 16px;
        line-height: 19px;
    }
    .footer-small {
        font-family: Work Sans;
        font-style: normal;
        font-weight: 300;
        font-size: 16px;
        line-height: 19px;
    }
    .contact-information > div > a > i {
        font-size: 36px;
    }
    @media only screen and (max-width: 600px) {
        .footer {
            flex-direction: column;
            text-align: center;
        }
  }
</style>

// components/user/Footer.vue
<template>
  <div
    class="flex flex-row justify-center w-full bg-dark-accent dark:bg-gray-900 p-16"
  >
    <div class="flex flex-col items-center">
      <h1 class="font-bold text-3xl">Kontakt oss</h1>
      <div class="pt-16 pb-8 flex flex-col items-center">
        <div class="font-bold">Tlf: +47 72 40 44 80</div>
        <div>E-post: post@oppdalskisenter.no</div>
      </div>
      <div class="py-8 flex flex-col items-center">
        <div class="font-bold">Gondolbane, Hovden</div>
        <div>Gamle Kongeveg 53, 7340 Oppdal</div>
      </div>
      <div class="py-8 flex flex-col items-center">
        <div class="font-bold">Servicesenter Vangslia</div>
        <div>Kjerkvegen 112, 7340 Oppdal</div>
      </div>
      <div class="py-8 flex flex-col items-center">
        <div class="flex flex-row pb-1">
          <a href="https://facebook.com/oppdal/">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="24"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <path
                d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"
              />
            </svg>
          </a>
          <div class="px-1"></div>
          <a href="https://instagram.com/oppdal_skisenter/">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="24"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <rect x="2" y="2" width="20" height="20" rx="5" ry="5" />
              <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
              <line x1="17.5" y1="6.5" x2="17.51" y2="6.5" />
            </svg>
          </a>
        </div>
        <div class="font-light text-sm">Oppdal skisenter © 2021</div>
      </div>
    </div>
  </div>
</template>
