// src/components/Navbar.svelte
<script>
  import { onMount } from "svelte";
  import Wrapper from "./max-wrapper.svelte";
  let comesFromMainSite = false;

  onMount(() => {
    comesFromMainSite = document.referrer.includes("oppdalskisenter");
  });
</script>

<Wrapper>
  <nav class="flex justify-between align-center py-4 w-full max-w-screen-xl">
    <a href="https://oppdalskisenter.no" class="p-2 rounded-xl dark:bg-gray-500">
      <img src="../../assets/logo.svg" alt="oppdalskisenter-logo" />
    </a>
  </nav>
</Wrapper>

// components/Navbar.vue
<template>
  <MaxWrapper>
    <nav class="flex justify-between align-center py-4 w-full max-w-screen-xl">
      <div v-if="comesFromMainSite">
        <a class="text-xl font-semibold hover:opacity-70 cursor-pointer" href="https://oppdalskisenter.no">Gå til oppdalskisenter.no</a>
      </div>
      <img class="mr-4" src="/assets/logo.svg" alt="oppdalskisenter-logo"/>
    </nav>
  </MaxWrapper>
</template>

<script>
export default {
  data() {
    return {
      comesFromMainSite: false
    }
  },
  mounted() {
    this.comesFromMainSite = document.referrer.includes('oppdalskisenter')
  }
}
</script>
