// pages/admin/login.vue
<template>
  <div
    class="absolute flex flex-col items-center h-full w-full font-sans dark:bg-gray-800 bg-white dark:text-white"
  >
    <max-wrapper class="w-full h-full">
      <div class="flex flex-col justify-center w-full h-full">
        <div class="flex flex-row justify-center items-center w-full h-full">
          <div class="w-full p-4 md:w-1/3 bg-gray-700 rounded-xl">
            <div class="p-2 flex flex-row w-full justify-center font-bold text-2xl">Logg inn</div>
            <div class="font-bold">Brukernavn</div>
            <input
              class="w-full p-2 rounded-lg text-gray-100 bg-gray-500"
              placeholder="Brukernavn"
              type="text"
              v-model="username"
            />
            <div class="py-1"></div>
            <div class="font-bold">Passord</div>
            <input
              class="w-full p-2 rounded-lg text-gray-100 bg-gray-500"
              placeholder="Passord"
              type="password"
              v-model="password"
            />
            <div class="py-1"></div>
            <div class="flex flex-row justify-end">
              <button class="p-2 bg-blue-400 rounded-xl" @click="login">Logg inn</button>
            </div>
          </div>
        </div>
      </div>
    </max-wrapper>
  </div>
</template>
<script>
import MaxWrapper from '../../components/user/MaxWrapper.vue';
import BASE_URL from '../../helpers/baseurl'
export default {
  components: { MaxWrapper },
  data: () => ({
    username: "",
    password: "",
  }),
  methods: {
    login() {
      fetch(BASE_URL + "/admin/login", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          username: this.username,
          password: this.password,
        }),
      })
        .then((res) => res.json())
        .then((res) => {
          if (res.token) {
            window.localStorage.setItem("token", res.token);
            this.$router.push("/admin");
          } else {
            alert("Invalid username or password");
          }
        });
    },
  },
};
</script>

// src/views/admin/Login.svelte
<script>
  import { UserIcon, LockIcon } from 'svelte-feather-icons'
  import { navigateTo } from 'svelte-router-spa'
  import { toast } from '../../stores/Toast'
  import config from '../../helpers/config';
  import OFetch from '../../helpers/fetch'
  import Toast from '../../components/admin/Toast.svelte'
  let username = ""
  let password = ""

  async function login() {
    const body = {
      "username": username,
      "password": password
    }
    try {
      let response = await OFetch(
        `${config.BASE_URL}/admin/login`,
        "POST",
        body
      )
      const user = {
        username: response.user.username,
        token: response.token
      }
      localStorage.setItem("user", JSON.stringify(user))
      navigateTo("/admin")
    } catch (err) {
      console.log(err)
      toast.setToast('Feil brukernavn eller passord', 'error');
    }
  }

  const onKeyPress = e => {
    if (e.charCode === 13) login();
  }

</script>
<div class="login">
  <div>
    <h3 class="header">Logg inn</h3>
    <div class="input-wrapper">
      <UserIcon size="28" />
      <input
        type="text"
        class=""
        placeholder="Brukernavn"
        bind:value={username}
        on:keypress={onKeyPress}
        autocomplete="off"
        autocorrect="off"
        autocapitalize="off"
        spellcheck="false"
      />
    </div>
    <div class="input-wrapper">
      <LockIcon size="28" />
      <input
        type="password"
        placeholder="Passord"
        bind:value={password}
        on:keypress={onKeyPress}
      />
    </div>
    <div class="input-wrapper">
      <button class="button" on:click={login}>
        Login
      </button>
    </div>
  </div>
  <Toast/>
</div>

<style>
  .login {
    display: flex;
    justify-content: center;
    align-content: center;
    align-items: center;
    height: 50vh;
  }
  .header {
    font-size: 32px;
    color: #004A7C;
    text-align: center;
  }

  .input-wrapper {
    display: flex;
    margin-top: 10px;
  }
  .input-wrapper > input {
    min-height: 30px;
  }
  .button {
    width: 100%;
    cursor: pointer;
  }
</style>
